# Generated by Django 5.1.3 on 2024-11-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavor_suggestion', models.TextField(blank=True)),
                ('Allergy_concerns', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Season', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Expiry', models.DateField()),
            ],
        ),
    ]
